### ISSUE TITLE
Readme: Provide (one) example(s)

### ISSUE THREAD

**Issue by rokdd** [Josef-Friedrich/audiorename#1]
I am not totally stupid (or I hope so) but it is very hard to understand the structure of the arguments you designed. Can you provide like a usual example which created subfolder by some criteria and rename the files? Or do you have blog where these can be found?

**Comment by Josef-Friedrich** [comment]
Unfortunately I have not written a blog post about audiorename. I have tried to put all informations into the command line documentation `--help` - as I just noticed with little success ;-)

Please use the `-d`  (--dry-run) option first

Basic example

```
cd my-chaotic-music-collection
audiorenamer -d .
```

More advanced example:

```
audiorenamer -d -f '$artist/$album/$track $title' --target /mnt/hd/my-organized-music-collection .
```

Very advanced example: 

```
audiorenamer -d -f '$ar_initial_artist/%shorten{$ar_combined_artist_sort}/%shorten{$ar_combined_album}%ifdefnotempty{ar_combined_year,_${ar_combined_year}}/${ar_combined_disctrack}_%shorten{$title}' .
```

**Comment by Josef-Friedrich** [comment]
If this examples are useful, I can add them to the README file. Or if you discover useful examples please share them

**Comment by rokdd** [comment]
Thanks this was the plan if I discover something useful so far!

**Comment by rokdd** [comment]
I have the following commandline and it always created in the first level a folder with the first character of the artist?

`audiorenamer -V -b -k -r -a -f '$artist/$album/%num{$track,2} $title'  /var/xx/Jukebox`

For example:
`/var/xx/Jukebox/j/Johann Sebastian Bach/_[]/59_6e Kantate - 11 Choral - Nun Seid Ihr Wohl Gerochen_.m4a`

**Comment by Josef-Friedrich** [comment]
If you use both options `-k` and `-f`, then `-f` is ignored

From the --help message:

`-k`: Use the default format for classical music. If you use this option, both parameters (--format and --compilation) have no effect. Classical music is sorted by the lastname of the composer.

The format string used  with -k is hard coded in:

https://github.com/Josef-Friedrich/audiorename/blob/8546ddee49e14446c8c7162d509919af7d670551/audiorename/job.py#L96-L100

audiorenamer has no detection for classical music. -k just uses a different default format string which I think is better suited for classical music

**Comment by rokdd** [comment]
Okay thanks for your clarifications. Your code is really nice but was a bit hard to understand at the beginning. When you think that you will accept I can create a pull request with the following changes:

- the best format function was not working when the format was not in the list
- added argument to define a custom classical format additional to the common one
- added argument to define which genres are classical so it switches automatically between classical and non-classical in one run

**Comment by Josef-Friedrich** [comment]
Your proposals are promising. I lock forward to your pull requests and I will accept them.

**Comment by rokdd** [comment]
Well lets discuss at PR further.
