### ISSUE TITLE
Files want to get moved out of main folder

### ISSUE THREAD

**Issue by rokdd** [Josef-Friedrich/audiorename#10]
Same files are always ending up in my root directory, outside of the "main" folder. How can this be happen or doing I am something wrong at config?
> Jukebox/00  O Heiland, reiß die Himmel auf.mp3
>     Move
>         […]/var/xx/xx/xx/xx/Jukebox/00  O Heiland, reiß die Himmel auf.mp3
>         to:
>         […]//00  O Heiland, reiß die Himmel auf.mp3

And the arguments:

`audiorenamer -a --best-format --backup -p='/var/xx/xx/xx/xx/JukeBackup' --soundtrack='$album/%num{$track,2} $title' --genre-classical='Piano,Klassische Musik,Classical,Classical Music,Classical Instrumental,Classical Piano,Classic Piano,Classic Ballet,Classical Ballet,Oper,Opera,Klavier' --format-classical='$ar_combined_composer/%shorten{$ar_combined_work_top,48}_[%shorten{$ar_classical_performer,32}]/${ar_combined_disctrack}_%shorten{$ar_classical_title,64}_%shorten{$acoustid_id,8}' -f '$artist/$album/%num{$track,2} $title' /var/xx/xx/xx/xx/Jukebox`

**Comment by Josef-Friedrich** [comment]
I suspect that the genre detection does not work in this example. audiorame uses the -f '$artist/$album/%num{$track,2} $title' format string and the artist and album tags are empty.  This is how two consecutive slashes are created. Maybe  python interprets two slashes as the root directory? Have you used `audiorenamer  --debug` to see all tags?

**Comment by rokdd** [comment]
Ok well now I made it to understand it better - that the genre is not applying was intended but $artist/$album are empty:
![image](https://user-images.githubusercontent.com/640866/158448952-ecc67b99-81e8-4cb6-bc77-d92df2445ad9.png)

I changed the pattern now so it works with a condition for the slash. I Think it would be better to catch this somewhere.

**Comment by Josef-Friedrich** [comment]
Maybe the design decision to fill empty fields with an empty string was not a good idea.

https://github.com/Josef-Friedrich/audiorename/blob/9578a4523c4d8b6fec8cd22ac6e39cfa4ed090f3/audiorename/meta.py#L340-L355

If I were to remove these lines, 

https://github.com/Josef-Friedrich/audiorename/blob/9578a4523c4d8b6fec8cd22ac6e39cfa4ed090f3/audiorename/meta.py#L352-L353

the result would look like this

`$album/$artist/00 O Heiland, reiß die Himmel auf.mp3` Would this be better?

**Comment by rokdd** [comment]
Sorry I was in holidays.. I guess to change the handling of the string does not really help. It will result in an empty and path like `"//.." `. I guess what would help is to have regular expression to avoid empty folders? Or another solution with more "impact" would be to split the path by the separator and generate the path with `os.join`?

**Comment by Josef-Friedrich** [comment]
Welcome back. I hope you had a nice vacation. In the meantime, I even believe that the audio file ends up in the root directory if the resulting file path begins with a single slash. 

What I wanted to express with my last comment: Wouldn't it have helped you to find the error (the missing tags) if the audio file hadn't ended up in the root directory, but in a folder called `$album` containing another  folder `$artist` and so on. 

`audiorename` uses  the template engine from the beets project (https://github.com/Josef-Friedrich/tmep). This library does not expand empty variables and leaves the variable unchanged: From the documentation:

> Also, the templates always behave like the safe_substitute method in the standard library: unknown symbols are left intact.

**Comment by Josef-Friedrich** [comment]
I can think of an option that throws an error if the resulting path starts with `/`, for example `--no-resulting-root-path`? Pull requests are very welcome!

**Comment by rokdd** [comment]
For me it was "enough" to get a exception which was fired because the root directory is not writeable ;-) I guess for the moment it would be the best to check whether the path gets out of the specified path. I do not understand why it is necessary to have a path outside of the main directory possible. By default a `--no-resulting-root-path` should be True ?

**Comment by Josef-Friedrich** [comment]
>  I do not understand why it is necessary to have a path outside of the main directory possible. 

You right. I agree with you: There is an option `--target`

Or we just remove leading slashes from the resulting path? That would probably be the easiest way to go ...

**Comment by rokdd** [comment]
Well or throw an Exception when the first character is a directory separator? I assume that nobody runs this script totally unattended? Or skip the file like you do when you have a broken file detected?
