### ISSUE TITLE
AttributeError: module 'phrydy' has no attribute 'doc'

### ISSUE THREAD

**Issue by kikoenai** [Josef-Friedrich/audiorename#11]
Hello! Cool project you have! I tried to download it via (Debian 11) pip for python version 3.9 (therefore I am running audiorename 2.1.1). When I use any command of the program I get:

```bash
<my name>@<my-computer>:~/Music/Various-Unknown_Album$ audiorenamer -h
Traceback (most recent call last):
  File "/home/<my name>/.local/bin/audiorenamer", line 3, in <module>
    from audiorename import execute
  File "/home/<my name>/.local/lib/python3.9/site-packages/audiorename/__init__.py", line 4, in <module>
    from .args import parse_args
  File "/home/<my name>/.local/lib/python3.9/site-packages/audiorename/args.py", line 82, in <module>
    all_fields = phrydy.doc.merge_fields(phrydy.doc.fields, fields)
AttributeError: module 'phrydy' has no attribute 'doc'
```
I have double checked the dependencies for the project and they seem to be normal. I might be doing something completely wrong I am not sure. Please let me know if there is any solution to this or if I can provide any more information.

Thank you in advance.

**Comment by Josef-Friedrich** [comment]
could you please try the latest version

```
pip3 install audiorename==3.0.0
```

**Comment by kikoenai** [comment]
Thank you for the fast reply! I updated the software and it works perfectly now! Thank you very much for the quick fix and new version! :-)
